<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.example</groupId>
	<artifactId>atividade-completa</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>atividade-completa</name>
	<description>Microsservicos de Pecas, Clientes e Representantes com Spring Cloud</description>
	<modules>
		<module>config-server</module>
		<module>eureka-server</module>
		<module>gateway</module>
		<module>pecas-service</module>
		<module>clientes-service</module>
		<module>representantes-service</module>
	</modules>
</project>
